import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Aura Signature Tee',
    description: 'A premium heavy-weight cotton tee with a relaxed fit. Designed for ultimate comfort and style.',
    price: 45,
    category: 'unisex',
    subcategory: 'tops',
    images: ['https://picsum.photos/seed/aura1/800/1000', 'https://picsum.photos/seed/aura1-2/800/1000'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }],
    stock: 100,
    rating: 4.8,
    reviewsCount: 124,
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: '2',
    name: 'Minimalist Windbreaker',
    description: 'Water-resistant, lightweight windbreaker perfect for transitional seasons.',
    price: 120,
    category: 'men',
    subcategory: 'outerwear',
    images: ['https://picsum.photos/seed/aura2/800/1000'],
    sizes: ['M', 'L', 'XL'],
    colors: [{ name: 'Slate', hex: '#708090' }],
    stock: 45,
    rating: 4.5,
    reviewsCount: 56,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: '3',
    name: 'Ethereal Silk Dress',
    description: 'A flowing, elegant silk dress designed for sophisticated evenings.',
    price: 210,
    category: 'women',
    subcategory: 'dresses',
    images: ['https://picsum.photos/seed/aura3/800/1000'],
    sizes: ['XS', 'S', 'M'],
    colors: [{ name: 'Emerald', hex: '#50C878' }],
    stock: 20,
    rating: 4.9,
    reviewsCount: 89,
    isNewArrival: false,
    isBestSeller: true,
  }
];
